apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.namespace.protocol }}
    targetPort: {{ .Values.namespace.targetPort }}
  type: {{ .Values.namespace.type }}
